styles:
  templates:
    layoutRootPath: 'EXT:plugsy/Resources/Private/PageView/Layouts/'
    partialRootPath: 'EXT:plugsy/Resources/Private/PageView/Partials/'
    templateRootPath: 'EXT:plugsy/Resources/Private/PageView/ContentElements/'
