services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3Incubator\SurfcampBase\:
    resource: '../Classes/*'

  TYPO3Incubator\SurfcampBase\EventListener\MoveHtmlAfterUpload:
    tags:
      - name: event.listener
        identifier: 'surfcamp-base/move-html-after-upload'
        event: TYPO3\CMS\Core\Resource\Event\BeforeFileCreatedEvent
