services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3Incubator\SurfcampBase\:
    resource: '../Classes/*'

  \TYPO3Incubator\SurfcampBase\DataProcessors\ApiAggregationDataProcessor:
    tags:
      - name: 'data.processor'
