services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  _instanceof:
    TYPO3Incubator\SurfcampBase\Http\ContentTypeHandlers\HandlerInterface:
      tags: [ 'handler' ]
    TYPO3Incubator\SurfcampBase\Http\Client\ClientInterface:
      tags: [ 'client' ]

  TYPO3Incubator\SurfcampBase\:
    resource: '../Classes/*'

  TYPO3Incubator\SurfcampBase\Http\ContentTypeHandlers\ResponseHandler:
    arguments: [ !tagged_iterator handler ]

  TYPO3Incubator\SurfcampBase\Http\Client\Client:
    arguments: [ !tagged_iterator client ]

  querybuilder.tx_surfcampbase_api_endpoint:
    class: 'TYPO3\CMS\Core\Database\Query\QueryBuilder'
    factory:
      - '@TYPO3\CMS\Core\Database\ConnectionPool'
      - 'getQueryBuilderForTable'
    arguments:
      - 'tx_surfcampbase_api_endpoint'

  querybuilder.tx_surfcampbase_api_fieldmapping:
    class: 'TYPO3\CMS\Core\Database\Query\QueryBuilder'
    factory:
      - '@TYPO3\CMS\Core\Database\ConnectionPool'
      - 'getQueryBuilderForTable'
    arguments:
      - 'tx_surfcampbase_api_fieldmapping'

  TYPO3Incubator\SurfcampBase\Repository\ApiEndpointRepository:
    public: true
    arguments:
      $queryBuilder: '@querybuilder.tx_surfcampbase_api_endpoint'

  cache.surfcamp_base_api_response:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: [ '@TYPO3\CMS\Core\Cache\CacheManager', 'getCache' ]
    arguments: [ 'surfcamp_base_api_response' ]

  TYPO3Incubator\SurfcampBase\Service\CacheService:
    arguments:
      $cache: '@cache.surfcamp_base_api_response'

  TYPO3Incubator\SurfcampBase\Repository\ApiFieldMappingRepository:
    public: true
    arguments:
      $queryBuilder: '@querybuilder.tx_surfcampbase_api_fieldmapping'
