services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3Incubator\SurfcampBase\:
    resource: '../Classes/*'

  TYPO3Incubator\SurfcampBase\Repository\ApiBaseRepository:
    public: true

  TYPO3Incubator\SurfcampBase\Repository\ApiEndpointRepository:
    public: true
