categories:
  SurfcampBase:
    label: 'Surfcamp Base'

settings:
  cache.response.lifetime:
    label: 'Response Cache Lifetime'
    description: 'Response Cache Lifetime'
    category: SurfcampBase
    type: int
    default: 600
