services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  _instanceof:
    TYPO3Incubator\Plugsy\Http\ContentTypeHandlers\HandlerInterface:
      tags: [ 'handler' ]
    TYPO3Incubator\Plugsy\Http\Client\ClientInterface:
      tags: [ 'client' ]

  TYPO3Incubator\Plugsy\:
    resource: '../Classes/*'

  TYPO3Incubator\Plugsy\Http\ContentTypeHandlers\ResponseHandler:
    arguments: [ !tagged_iterator handler ]

  TYPO3Incubator\Plugsy\Http\Client\Client:
    arguments: [ !tagged_iterator client ]

  querybuilder.tx_plugsy_api_endpoint:
    class: 'TYPO3\CMS\Core\Database\Query\QueryBuilder'
    factory:
      - '@TYPO3\CMS\Core\Database\ConnectionPool'
      - 'getQueryBuilderForTable'
    arguments:
      - 'tx_plugsy_api_endpoint'

  TYPO3Incubator\Plugsy\Repository\ApiEndpointRepository:
    public: true
    arguments:
      $queryBuilder: '@querybuilder.tx_plugsy_api_endpoint'

  cache.plugsy_api_response:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: [ '@TYPO3\CMS\Core\Cache\CacheManager', 'getCache' ]
    arguments: [ 'plugsy_api_response' ]

  TYPO3Incubator\Plugsy\Service\CacheService:
    arguments:
      $cache: '@cache.plugsy_api_response'

  querybuilder.tx_plugsy_api_fieldmapping:
    class: 'TYPO3\CMS\Core\Database\Query\QueryBuilder'
    factory:
      - '@TYPO3\CMS\Core\Database\ConnectionPool'
      - 'getQueryBuilderForTable'
    arguments:
      - 'tx_plugsy_api_fieldmapping'

  TYPO3Incubator\Plugsy\Repository\ApiMappingRepository:
    public: true
    arguments:
      $queryBuilder: '@querybuilder.tx_plugsy_api_fieldmapping'
